@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTUzMzU2OTl9.cfeW1LU1_VEI9E4HisrUXXQxzUxMMtXDl1fw4b9RLz0

### Products index
GET {{host}}/products.json

### Products create
POST {{host}}/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Test name",
  "price": "10",
  "description": "test description",
  "supplier_id": 1
}

### Products show
GET {{host}}/products/6.json

### Products update
PATCH {{host}}/products/2.json
Content-Type: application/json

{
  "name": "UFO Abduction Earrings",
  "price": "15",
  "description": "Lock up your cows! The aliens are on their way."
}

### Product destroy
DELETE {{host}}/products/6.json
Authorization: Bearer {{jwt}}

### Users create (signup)
POST {{host}}/users.json
Content-Type: application/json

{
  "name": "Cait Dalton",
  "email": "disconerds@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{host}}/sessions.json
Content-Type: application/json

{
  "email": "disconerds@gmail.com",
  "password": "password"
}

### Order Create
POST {{host}}/orders.json 
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": "4",
  "quantity": "2"
}

### Order Show
GET {{host}}/orders/12.json
Authorization: Bearer {{jwt}}

### Order Index
GET {{host}}/orders.json
Authorization: Bearer {{jwt}}

### CartedProduct Index
GET {{host}}/carted_products.json
Authorization: Bearer {{jwt}}

### CartedProduct Create
POST {{host}}/carted_products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": "1",
  "quantity": "4",
  "status": "carted"
}

### CartedProduct Destroy
DELETE {{host}}/carted_products/7.json
Authorization: Bearer {{jwt}}