### Products index
GET http://localhost:3000/products.json

### Products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Strawberry Dress",
  "price": "440",
  "image_url": "placeholder",
  "description": "the iconic matoshi strawberry dress"
}

### Products show
GET http://localhost:3000/products/7.json

### Products update
PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "price": "550",
  "description": "The famous Matoshi Strawberry Dress"
}

### Product destroy
DELETE http://localhost:3000/products/6.json