### Products index
GET http://localhost:3000/products.json

### Products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Strawberry Dress",
  "price": "440",
  "description": "the iconic matoshi strawberry dress"
}

### Products show
GET http://localhost:3000/products/1.json

### Products update
PATCH http://localhost:3000/products/2.json
Content-Type: application/json

{
  "name": "UFO Abduction Earrings",
  "price": "15",
  "description": "Lock up your cows! The aliens are on their way."
}

### Product destroy
DELETE http://localhost:3000/products/6.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}